version: "3"

services:
  servas:
    image: beromir/servas
    container_name: servas
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./.env:/app/.env
      - servas-db-sqlite:/app/database

volumes:
  servas-db-sqlite:
